### ISSUE TITLE
AWS XRAY library should be either dependency or peer-dependency

### ISSUE THREAD

**Issue by healqq** [lifeomic/graphql-resolvers-xray-tracing#39]
Right now it's a dev dependency, but it's required in result file

**Comment by mdlavin** [comment]
It looks like it's a peer dependency right now. Checkout https://github.com/lifeomic/graphql-resolvers-xray-tracing/blob/master/package.json#L68

**Comment by healqq** [comment]
hm, that's true... for some reason it didn't mention it during npm install. Maybe because it's in both dev and peer dependencies.
