### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by stevenmusumeche** [lifeomic/graphql-resolvers-xray-tracing#49]
Hello, and thanks for this project.  I added this to a graphql server that runs on Lambda and it works great.  However, I can't run my server locally.  I added this conditional to make it work.  Is this something you'd consider adding to the library?

```typescript
if (process.env.AWS_LAMBDA_FUNCTION_NAME) {
  traceResolvers(schema);
}
```

**Comment by mdlavin** [comment]
Looks like a great addition, would you be interested in putting a PR up to add support for that?

**Comment by stevenmusumeche** [comment]
I'd be happy to, although now I'm wondering about users who aren't running within Lambda.

**Comment by mdlavin** [comment]
Good point. Is it worth documenting your approach in the README for other users to find?

**Comment by stevenmusumeche** [comment]
PR here: https://github.com/lifeomic/graphql-resolvers-xray-tracing/pull/53
