### ISSUE TITLE
Error on tsc

### ISSUE THREAD

**Issue by danilobuerger** [lifeomic/graphql-resolvers-xray-tracing#69]
When running tsc I am getting the following error:

```
❯ yarn run tsc --noEmit
yarn run v1.22.10
$ node_modules/.bin/tsc --noEmit
node_modules/@lifeomic/graphql-resolvers-xray-tracing/src/traceResolvers.ts:26:23 - error TS1196: Catch clause variable cannot have a type annotation.

26       } catch (error: any) {
                         ~~~


Found 1 error.
```

**Comment by mdlavin** [comment]
Interesting, it just be some new strictness in the TypeScript compiler. If you want to put a PR up to fix it, I'd be happy to merge it and release a new version

**Comment by mikemeerschaert** [comment]
I just submitted a PR with a fix for this, would you mind merging when you get a chance?

Thanks!

**Comment by mdlavin** [comment]
I merged your PR and it should get released soon

**Comment by mikemeerschaert** [comment]
Thanks for getting that added so fast, nobody else on my team even noticed an issue when they built my latest commit!
