### ISSUE TITLE
Remove is-promise dependency?

### ISSUE THREAD

**Issue by jplock** [lifeomic/graphql-resolvers-xray-tracing#9]
Why not remove an external dependency on `is-promise` and implement:

```
function isPromise(obj) {
  return !!obj && (typeof obj === 'object' || typeof obj === 'function') && typeof obj.then === 'function';
}
```

in index.js itself.

**Comment by mdlavin** [comment]
I didn't want to try duplicating the logic of Promise detection if some other project provided the logic already. I don't want to keep up with the most appropriate way to detect a Promise as things change. If there is a better dependency to use I'm up for switching.
